version: '3'

tasks:
    lint:
      cmds:
        - golangci-lint run --timeout 5m0s

    build:
      cmds:
        - go build -o build/server cmd/main.go

    run:
      cmds:
        - go run cmd/main.go

    swagdocs:
      cmds:
        - swag fmt && swag init --generalInfo server.go --dir internal/controller/fiber,internal/domain/models --output internal/controller/fiber/docs --outputTypes go,json
